# The alacritty configuration file
# Used by Rivallix

# Importing the terminal theme
import = [
    "~/.config/alacritty/themes/themes/horizon-dark.toml"           # Perhaps switch to another theme.
]

live_config_reload = true

# Offer IPC using alacritty msg
# Default: true
ipc_socket = false

[env]
TERM = "alacritty"

[window]
title = "Terminal"							                	    # Custom window title
dynamic_title = true							                    # Allow terminal applications to change Alacritty's window title.
dimensions = { columns = 130, lines = 35}		                    # Window dimensions (changes require restart).
position = "None"					                  			    # Window startup position.
padding = { x = 0, y = 0 } 						                    # Blank space added around the window in pixels.
opacity = 0.85									                    # Background opacity as a floating point number from 0.0 to 1.0.
startup_mode = "Windowed"					              	        # Startup mode (changes require restart).

[scrolling]
history = 100000

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
size = 11

[font.normal]
family = "JetBrains Mono"
style = "Regular"


[bell]
animation = "Ease"
duration = 0									                    # Disable the visual bell flash (Duration of the bell flash in ms).


[mouse]
hide_when_typing = true
